### ISSUE TITLE
Awesome list

### ISSUE THREAD

**Issue by KtorZ** [TheSmiths/ComponentsDocumentationGuidelines#2]
Make an "awesome list" of all working widgets, modules and libraries. 
To be in the list the component should:
- be well documented (i.e., close enough to the guidelines).
- compile in an app for every specified version.

**Comment by jcsomac** [comment]
What about Classic Development ?

**Comment by KtorZ** [comment]
What do you mean by "Classic" ?

**Comment by jcsomac** [comment]
Sorry... i was trying to post in the "To.BounceView" ...
